// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/hashtag/hashtag.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PredictRequest contains the event text and prediction options
type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventText     string                 `protobuf:"bytes,1,opt,name=event_text,json=eventText,proto3" json:"event_text,omitempty"`
	UseBart       *bool                  `protobuf:"varint,2,opt,name=use_bart,json=useBart,proto3,oneof" json:"use_bart,omitempty"`
	Threshold     *float64               `protobuf:"fixed64,3,opt,name=threshold,proto3,oneof" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_proto_hashtag_hashtag_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetEventText() string {
	if x != nil {
		return x.EventText
	}
	return ""
}

func (x *PredictRequest) GetUseBart() bool {
	if x != nil && x.UseBart != nil {
		return *x.UseBart
	}
	return false
}

func (x *PredictRequest) GetThreshold() float64 {
	if x != nil && x.Threshold != nil {
		return *x.Threshold
	}
	return 0
}

// HashtagScore represents a hashtag with its confidence score
type HashtagScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashtag       string                 `protobuf:"bytes,1,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashtagScore) Reset() {
	*x = HashtagScore{}
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashtagScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashtagScore) ProtoMessage() {}

func (x *HashtagScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashtagScore.ProtoReflect.Descriptor instead.
func (*HashtagScore) Descriptor() ([]byte, []int) {
	return file_proto_hashtag_hashtag_proto_rawDescGZIP(), []int{1}
}

func (x *HashtagScore) GetHashtag() string {
	if x != nil {
		return x.Hashtag
	}
	return ""
}

func (x *HashtagScore) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// PredictResponse contains the predicted hashtags
type PredictResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Suggested       []string               `protobuf:"bytes,1,rep,name=suggested,proto3" json:"suggested,omitempty"`
	Top_5           []*HashtagScore        `protobuf:"bytes,2,rep,name=top_5,json=top5,proto3" json:"top_5,omitempty"`
	InferenceTimeMs float64                `protobuf:"fixed64,3,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"`
	UsedBart        bool                   `protobuf:"varint,4,opt,name=used_bart,json=usedBart,proto3" json:"used_bart,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_proto_hashtag_hashtag_proto_rawDescGZIP(), []int{2}
}

func (x *PredictResponse) GetSuggested() []string {
	if x != nil {
		return x.Suggested
	}
	return nil
}

func (x *PredictResponse) GetTop_5() []*HashtagScore {
	if x != nil {
		return x.Top_5
	}
	return nil
}

func (x *PredictResponse) GetInferenceTimeMs() float64 {
	if x != nil {
		return x.InferenceTimeMs
	}
	return 0
}

func (x *PredictResponse) GetUsedBart() bool {
	if x != nil {
		return x.UsedBart
	}
	return false
}

// CollectDataRequest contains user feedback for incremental learning
type CollectDataRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventText        string                 `protobuf:"bytes,2,opt,name=event_text,json=eventText,proto3" json:"event_text,omitempty"`
	SelectedHashtags []string               `protobuf:"bytes,3,rep,name=selected_hashtags,json=selectedHashtags,proto3" json:"selected_hashtags,omitempty"`
	Timestamp        string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source           string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CollectDataRequest) Reset() {
	*x = CollectDataRequest{}
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectDataRequest) ProtoMessage() {}

func (x *CollectDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectDataRequest.ProtoReflect.Descriptor instead.
func (*CollectDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_hashtag_hashtag_proto_rawDescGZIP(), []int{3}
}

func (x *CollectDataRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CollectDataRequest) GetEventText() string {
	if x != nil {
		return x.EventText
	}
	return ""
}

func (x *CollectDataRequest) GetSelectedHashtags() []string {
	if x != nil {
		return x.SelectedHashtags
	}
	return nil
}

func (x *CollectDataRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *CollectDataRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// CollectDataResponse confirms data collection
type CollectDataResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SamplesCollected int32                  `protobuf:"varint,3,opt,name=samples_collected,json=samplesCollected,proto3" json:"samples_collected,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CollectDataResponse) Reset() {
	*x = CollectDataResponse{}
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectDataResponse) ProtoMessage() {}

func (x *CollectDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectDataResponse.ProtoReflect.Descriptor instead.
func (*CollectDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_hashtag_hashtag_proto_rawDescGZIP(), []int{4}
}

func (x *CollectDataResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CollectDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CollectDataResponse) GetSamplesCollected() int32 {
	if x != nil {
		return x.SamplesCollected
	}
	return 0
}

// HealthRequest is empty
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_hashtag_hashtag_proto_rawDescGZIP(), []int{5}
}

// HealthResponse contains service health information
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	NumHashtags   int32                  `protobuf:"varint,3,opt,name=num_hashtags,json=numHashtags,proto3" json:"num_hashtags,omitempty"`
	F1Score       float64                `protobuf:"fixed64,4,opt,name=f1_score,json=f1Score,proto3" json:"f1_score,omitempty"`
	Device        string                 `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hashtag_hashtag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_hashtag_hashtag_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *HealthResponse) GetNumHashtags() int32 {
	if x != nil {
		return x.NumHashtags
	}
	return 0
}

func (x *HealthResponse) GetF1Score() float64 {
	if x != nil {
		return x.F1Score
	}
	return 0
}

func (x *HealthResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

var File_proto_hashtag_hashtag_proto protoreflect.FileDescriptor

const file_proto_hashtag_hashtag_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/hashtag/hashtag.proto\x12\ahashtag\"\x8d\x01\n" +
	"\x0ePredictRequest\x12\x1d\n" +
	"\n" +
	"event_text\x18\x01 \x01(\tR\teventText\x12\x1e\n" +
	"\buse_bart\x18\x02 \x01(\bH\x00R\auseBart\x88\x01\x01\x12!\n" +
	"\tthreshold\x18\x03 \x01(\x01H\x01R\tthreshold\x88\x01\x01B\v\n" +
	"\t_use_bartB\f\n" +
	"\n" +
	"_threshold\"H\n" +
	"\fHashtagScore\x12\x18\n" +
	"\ahashtag\x18\x01 \x01(\tR\ahashtag\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\"\xa4\x01\n" +
	"\x0fPredictResponse\x12\x1c\n" +
	"\tsuggested\x18\x01 \x03(\tR\tsuggested\x12*\n" +
	"\x05top_5\x18\x02 \x03(\v2\x15.hashtag.HashtagScoreR\x04top5\x12*\n" +
	"\x11inference_time_ms\x18\x03 \x01(\x01R\x0finferenceTimeMs\x12\x1b\n" +
	"\tused_bart\x18\x04 \x01(\bR\busedBart\"\xaf\x01\n" +
	"\x12CollectDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"event_text\x18\x02 \x01(\tR\teventText\x12+\n" +
	"\x11selected_hashtags\x18\x03 \x03(\tR\x10selectedHashtags\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"t\n" +
	"\x13CollectDataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11samples_collected\x18\x03 \x01(\x05R\x10samplesCollected\"\x0f\n" +
	"\rHealthRequest\"\xa3\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12!\n" +
	"\fnum_hashtags\x18\x03 \x01(\x05R\vnumHashtags\x12\x19\n" +
	"\bf1_score\x18\x04 \x01(\x01R\af1Score\x12\x16\n" +
	"\x06device\x18\x05 \x01(\tR\x06device2\xe0\x01\n" +
	"\x0eHashtagService\x12D\n" +
	"\x0fPredictHashtags\x12\x17.hashtag.PredictRequest\x1a\x18.hashtag.PredictResponse\x12H\n" +
	"\vCollectData\x12\x1b.hashtag.CollectDataRequest\x1a\x1c.hashtag.CollectDataResponse\x12>\n" +
	"\vHealthCheck\x12\x16.hashtag.HealthRequest\x1a\x17.hashtag.HealthResponseB-Z+github.com/waydxd/Orbit-core/pkg/hashtag/pbb\x06proto3"

var (
	file_proto_hashtag_hashtag_proto_rawDescOnce sync.Once
	file_proto_hashtag_hashtag_proto_rawDescData []byte
)

func file_proto_hashtag_hashtag_proto_rawDescGZIP() []byte {
	file_proto_hashtag_hashtag_proto_rawDescOnce.Do(func() {
		file_proto_hashtag_hashtag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hashtag_hashtag_proto_rawDesc), len(file_proto_hashtag_hashtag_proto_rawDesc)))
	})
	return file_proto_hashtag_hashtag_proto_rawDescData
}

var file_proto_hashtag_hashtag_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_hashtag_hashtag_proto_goTypes = []any{
	(*PredictRequest)(nil),      // 0: hashtag.PredictRequest
	(*HashtagScore)(nil),        // 1: hashtag.HashtagScore
	(*PredictResponse)(nil),     // 2: hashtag.PredictResponse
	(*CollectDataRequest)(nil),  // 3: hashtag.CollectDataRequest
	(*CollectDataResponse)(nil), // 4: hashtag.CollectDataResponse
	(*HealthRequest)(nil),       // 5: hashtag.HealthRequest
	(*HealthResponse)(nil),      // 6: hashtag.HealthResponse
}
var file_proto_hashtag_hashtag_proto_depIdxs = []int32{
	1, // 0: hashtag.PredictResponse.top_5:type_name -> hashtag.HashtagScore
	0, // 1: hashtag.HashtagService.PredictHashtags:input_type -> hashtag.PredictRequest
	3, // 2: hashtag.HashtagService.CollectData:input_type -> hashtag.CollectDataRequest
	5, // 3: hashtag.HashtagService.HealthCheck:input_type -> hashtag.HealthRequest
	2, // 4: hashtag.HashtagService.PredictHashtags:output_type -> hashtag.PredictResponse
	4, // 5: hashtag.HashtagService.CollectData:output_type -> hashtag.CollectDataResponse
	6, // 6: hashtag.HashtagService.HealthCheck:output_type -> hashtag.HealthResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hashtag_hashtag_proto_init() }
func file_proto_hashtag_hashtag_proto_init() {
	if File_proto_hashtag_hashtag_proto != nil {
		return
	}
	file_proto_hashtag_hashtag_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hashtag_hashtag_proto_rawDesc), len(file_proto_hashtag_hashtag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hashtag_hashtag_proto_goTypes,
		DependencyIndexes: file_proto_hashtag_hashtag_proto_depIdxs,
		MessageInfos:      file_proto_hashtag_hashtag_proto_msgTypes,
	}.Build()
	File_proto_hashtag_hashtag_proto = out.File
	file_proto_hashtag_hashtag_proto_goTypes = nil
	file_proto_hashtag_hashtag_proto_depIdxs = nil
}
