// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: proto/calendar/agent.proto

package calendar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessMessageRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // Target user whose context/data is relevant
	Message   string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // Raw user message
	SessionId string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Optional session ID for context tracking
	// Optional: lightweight context hints the backend might pass
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., locale, channel, tenant
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMessageRequest) Reset() {
	*x = ProcessMessageRequest{}
	mi := &file_proto_calendar_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMessageRequest) ProtoMessage() {}

func (x *ProcessMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMessageRequest.ProtoReflect.Descriptor instead.
func (*ProcessMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProcessMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProcessMessageRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProcessMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMessageResponse) Reset() {
	*x = ProcessMessageResponse{}
	mi := &file_proto_calendar_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMessageResponse) ProtoMessage() {}

func (x *ProcessMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMessageResponse.ProtoReflect.Descriptor instead.
func (*ProcessMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessMessageResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ProcessMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProcessMessageResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetAgentStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // State scoped to a specific user/session
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Optional session scope
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStateRequest) Reset() {
	*x = GetAgentStateRequest{}
	mi := &file_proto_calendar_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStateRequest) ProtoMessage() {}

func (x *GetAgentStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStateRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetAgentStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAgentStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetAgentStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStateResponse) Reset() {
	*x = GetAgentStateResponse{}
	mi := &file_proto_calendar_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStateResponse) ProtoMessage() {}

func (x *GetAgentStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStateResponse.ProtoReflect.Descriptor instead.
func (*GetAgentStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetAgentStateResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *GetAgentStateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAgentStateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_calendar_agent_proto protoreflect.FileDescriptor

const file_proto_calendar_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/calendar/agent.proto\x12\x05agent\"\xee\x01\n" +
	"\x15ProcessMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.agent.ProcessMessageRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x16ProcessMessageResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"N\n" +
	"\x14GetAgentStateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"_\n" +
	"\x15GetAgentStateResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xa9\x01\n" +
	"\fAgentService\x12M\n" +
	"\x0eProcessMessage\x12\x1c.agent.ProcessMessageRequest\x1a\x1d.agent.ProcessMessageResponse\x12J\n" +
	"\rGetAgentState\x12\x1b.agent.GetAgentStateRequest\x1a\x1c.agent.GetAgentStateResponseB-Z+github.com/waydxd/Orbit-core/proto/calendarb\x06proto3"

var (
	file_proto_calendar_agent_proto_rawDescOnce sync.Once
	file_proto_calendar_agent_proto_rawDescData []byte
)

func file_proto_calendar_agent_proto_rawDescGZIP() []byte {
	file_proto_calendar_agent_proto_rawDescOnce.Do(func() {
		file_proto_calendar_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calendar_agent_proto_rawDesc), len(file_proto_calendar_agent_proto_rawDesc)))
	})
	return file_proto_calendar_agent_proto_rawDescData
}

var file_proto_calendar_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_calendar_agent_proto_goTypes = []any{
	(*ProcessMessageRequest)(nil),  // 0: agent.ProcessMessageRequest
	(*ProcessMessageResponse)(nil), // 1: agent.ProcessMessageResponse
	(*GetAgentStateRequest)(nil),   // 2: agent.GetAgentStateRequest
	(*GetAgentStateResponse)(nil),  // 3: agent.GetAgentStateResponse
	nil,                            // 4: agent.ProcessMessageRequest.MetadataEntry
}
var file_proto_calendar_agent_proto_depIdxs = []int32{
	4, // 0: agent.ProcessMessageRequest.metadata:type_name -> agent.ProcessMessageRequest.MetadataEntry
	0, // 1: agent.AgentService.ProcessMessage:input_type -> agent.ProcessMessageRequest
	2, // 2: agent.AgentService.GetAgentState:input_type -> agent.GetAgentStateRequest
	1, // 3: agent.AgentService.ProcessMessage:output_type -> agent.ProcessMessageResponse
	3, // 4: agent.AgentService.GetAgentState:output_type -> agent.GetAgentStateResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_calendar_agent_proto_init() }
func file_proto_calendar_agent_proto_init() {
	if File_proto_calendar_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calendar_agent_proto_rawDesc), len(file_proto_calendar_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calendar_agent_proto_goTypes,
		DependencyIndexes: file_proto_calendar_agent_proto_depIdxs,
		MessageInfos:      file_proto_calendar_agent_proto_msgTypes,
	}.Build()
	File_proto_calendar_agent_proto = out.File
	file_proto_calendar_agent_proto_goTypes = nil
	file_proto_calendar_agent_proto_depIdxs = nil
}
