// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: proto/calendar/calendar.proto

package calendar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix timestamp (seconds)
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // Unix timestamp (seconds)
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Attendees     []string               `protobuf:"bytes,8,rep,name=attendees,proto3" json:"attendees,omitempty"`
	Recurrence    string                 `protobuf:"bytes,9,opt,name=recurrence,proto3" json:"recurrence,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"` // e.g., "confirmed", "tentative", "cancelled"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Event) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Event) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Event) GetAttendees() []string {
	if x != nil {
		return x.Attendees
	}
	return nil
}

func (x *Event) GetRecurrence() string {
	if x != nil {
		return x.Recurrence
	}
	return ""
}

func (x *Event) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Attendees     []string               `protobuf:"bytes,7,rep,name=attendees,proto3" json:"attendees,omitempty"`
	Recurrence    string                 `protobuf:"bytes,8,opt,name=recurrence,proto3" json:"recurrence,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateEventRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CreateEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateEventRequest) GetAttendees() []string {
	if x != nil {
		return x.Attendees
	}
	return nil
}

func (x *CreateEventRequest) GetRecurrence() string {
	if x != nil {
		return x.Recurrence
	}
	return ""
}

func (x *CreateEventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CreateEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // Optional filter by status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetEventsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetEventsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetEventsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetEventsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetEventsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Attendees     []string               `protobuf:"bytes,8,rep,name=attendees,proto3" json:"attendees,omitempty"`
	Recurrence    string                 `protobuf:"bytes,9,opt,name=recurrence,proto3" json:"recurrence,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UpdateEventRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *UpdateEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateEventRequest) GetAttendees() []string {
	if x != nil {
		return x.Attendees
	}
	return nil
}

func (x *UpdateEventRequest) GetRecurrence() string {
	if x != nil {
		return x.Recurrence
	}
	return ""
}

func (x *UpdateEventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *UpdateEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAvailableSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"` // Duration in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableSlotsRequest) Reset() {
	*x = GetAvailableSlotsRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableSlotsRequest) ProtoMessage() {}

func (x *GetAvailableSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableSlotsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableSlotsRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{9}
}

func (x *GetAvailableSlotsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAvailableSlotsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetAvailableSlotsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetAvailableSlotsRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type TimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{10}
}

func (x *TimeSlot) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TimeSlot) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetAvailableSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*TimeSlot            `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableSlotsResponse) Reset() {
	*x = GetAvailableSlotsResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableSlotsResponse) ProtoMessage() {}

func (x *GetAvailableSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableSlotsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableSlotsResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{11}
}

func (x *GetAvailableSlotsResponse) GetSlots() []*TimeSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *GetAvailableSlotsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAvailableSlotsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCalendarDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Categories    []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"` // Optional: filter by event categories
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCalendarDataRequest) Reset() {
	*x = GetCalendarDataRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCalendarDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCalendarDataRequest) ProtoMessage() {}

func (x *GetCalendarDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCalendarDataRequest.ProtoReflect.Descriptor instead.
func (*GetCalendarDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{12}
}

func (x *GetCalendarDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCalendarDataRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetCalendarDataRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetCalendarDataRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type GetCalendarDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCalendarDataResponse) Reset() {
	*x = GetCalendarDataResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCalendarDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCalendarDataResponse) ProtoMessage() {}

func (x *GetCalendarDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCalendarDataResponse.ProtoReflect.Descriptor instead.
func (*GetCalendarDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{13}
}

func (x *GetCalendarDataResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetCalendarDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCalendarDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAvailabilityRequest) Reset() {
	*x = GetUserAvailabilityRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAvailabilityRequest) ProtoMessage() {}

func (x *GetUserAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetUserAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserAvailabilityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserAvailabilityRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetUserAvailabilityRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type AvailabilityStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Available         bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Reason            string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ConflictingEvents []*Event               `protobuf:"bytes,3,rep,name=conflicting_events,json=conflictingEvents,proto3" json:"conflicting_events,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AvailabilityStatus) Reset() {
	*x = AvailabilityStatus{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityStatus) ProtoMessage() {}

func (x *AvailabilityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityStatus.ProtoReflect.Descriptor instead.
func (*AvailabilityStatus) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{15}
}

func (x *AvailabilityStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *AvailabilityStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AvailabilityStatus) GetConflictingEvents() []*Event {
	if x != nil {
		return x.ConflictingEvents
	}
	return nil
}

type GetUserAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *AvailabilityStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAvailabilityResponse) Reset() {
	*x = GetUserAvailabilityResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAvailabilityResponse) ProtoMessage() {}

func (x *GetUserAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*GetUserAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserAvailabilityResponse) GetStatus() *AvailabilityStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetUserAvailabilityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserAvailabilityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"` // Free-form query string (e.g., "meetings with john")
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`   // Optional tags to filter by
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsRequest) Reset() {
	*x = QueryEventsRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest) ProtoMessage() {}

func (x *QueryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{17}
}

func (x *QueryEventsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryEventsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryEventsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryEventsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryEventsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type QueryEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsResponse) Reset() {
	*x = QueryEventsResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse) ProtoMessage() {}

func (x *QueryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{18}
}

func (x *QueryEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryEventsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *QueryEventsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryEventsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_calendar_calendar_proto protoreflect.FileDescriptor

const file_proto_calendar_calendar_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/calendar/calendar.proto\x12\bcalendar\"\x94\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1c\n" +
	"\tattendees\x18\b \x03(\tR\tattendees\x12\x1e\n" +
	"\n" +
	"recurrence\x18\t \x01(\tR\n" +
	"recurrence\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"\x91\x02\n" +
	"\x12CreateEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x1c\n" +
	"\tattendees\x18\a \x03(\tR\tattendees\x12\x1e\n" +
	"\n" +
	"recurrence\x18\b \x01(\tR\n" +
	"recurrence\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"p\n" +
	"\x13CreateEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.calendar.EventR\x05event\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"}\n" +
	"\x10GetEventsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"p\n" +
	"\x11GetEventsResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa1\x02\n" +
	"\x12UpdateEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1c\n" +
	"\tattendees\x18\b \x03(\tR\tattendees\x12\x1e\n" +
	"\n" +
	"recurrence\x18\t \x01(\tR\n" +
	"recurrence\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"p\n" +
	"\x13UpdateEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.calendar.EventR\x05event\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"=\n" +
	"\x12DeleteEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"I\n" +
	"\x13DeleteEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x89\x01\n" +
	"\x18GetAvailableSlotsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\"D\n" +
	"\bTimeSlot\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\"y\n" +
	"\x19GetAvailableSlotsResponse\x12(\n" +
	"\x05slots\x18\x01 \x03(\v2\x12.calendar.TimeSlotR\x05slots\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8b\x01\n" +
	"\x16GetCalendarDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\"v\n" +
	"\x17GetCalendarDataResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"o\n" +
	"\x1aGetUserAvailabilityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\"\x8a\x01\n" +
	"\x12AvailabilityStatus\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12>\n" +
	"\x12conflicting_events\x18\x03 \x03(\v2\x0f.calendar.EventR\x11conflictingEvents\"\x87\x01\n" +
	"\x1bGetUserAvailabilityResponse\x124\n" +
	"\x06status\x18\x01 \x01(\v2\x1c.calendar.AvailabilityStatusR\x06status\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x91\x01\n" +
	"\x12QueryEventsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"\x93\x01\n" +
	"\x13QueryEventsResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\x99\x03\n" +
	"\x0fCalendarService\x12J\n" +
	"\vCreateEvent\x12\x1c.calendar.CreateEventRequest\x1a\x1d.calendar.CreateEventResponse\x12D\n" +
	"\tGetEvents\x12\x1a.calendar.GetEventsRequest\x1a\x1b.calendar.GetEventsResponse\x12J\n" +
	"\vUpdateEvent\x12\x1c.calendar.UpdateEventRequest\x1a\x1d.calendar.UpdateEventResponse\x12J\n" +
	"\vDeleteEvent\x12\x1c.calendar.DeleteEventRequest\x1a\x1d.calendar.DeleteEventResponse\x12\\\n" +
	"\x11GetAvailableSlots\x12\".calendar.GetAvailableSlotsRequest\x1a#.calendar.GetAvailableSlotsResponse2\x9d\x02\n" +
	"\x13CalendarDataService\x12V\n" +
	"\x0fGetCalendarData\x12 .calendar.GetCalendarDataRequest\x1a!.calendar.GetCalendarDataResponse\x12b\n" +
	"\x13GetUserAvailability\x12$.calendar.GetUserAvailabilityRequest\x1a%.calendar.GetUserAvailabilityResponse\x12J\n" +
	"\vQueryEvents\x12\x1c.calendar.QueryEventsRequest\x1a\x1d.calendar.QueryEventsResponseB-Z+github.com/waydxd/Orbit-core/proto/calendarb\x06proto3"

var (
	file_proto_calendar_calendar_proto_rawDescOnce sync.Once
	file_proto_calendar_calendar_proto_rawDescData []byte
)

func file_proto_calendar_calendar_proto_rawDescGZIP() []byte {
	file_proto_calendar_calendar_proto_rawDescOnce.Do(func() {
		file_proto_calendar_calendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calendar_calendar_proto_rawDesc), len(file_proto_calendar_calendar_proto_rawDesc)))
	})
	return file_proto_calendar_calendar_proto_rawDescData
}

var file_proto_calendar_calendar_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_calendar_calendar_proto_goTypes = []any{
	(*Event)(nil),                       // 0: calendar.Event
	(*CreateEventRequest)(nil),          // 1: calendar.CreateEventRequest
	(*CreateEventResponse)(nil),         // 2: calendar.CreateEventResponse
	(*GetEventsRequest)(nil),            // 3: calendar.GetEventsRequest
	(*GetEventsResponse)(nil),           // 4: calendar.GetEventsResponse
	(*UpdateEventRequest)(nil),          // 5: calendar.UpdateEventRequest
	(*UpdateEventResponse)(nil),         // 6: calendar.UpdateEventResponse
	(*DeleteEventRequest)(nil),          // 7: calendar.DeleteEventRequest
	(*DeleteEventResponse)(nil),         // 8: calendar.DeleteEventResponse
	(*GetAvailableSlotsRequest)(nil),    // 9: calendar.GetAvailableSlotsRequest
	(*TimeSlot)(nil),                    // 10: calendar.TimeSlot
	(*GetAvailableSlotsResponse)(nil),   // 11: calendar.GetAvailableSlotsResponse
	(*GetCalendarDataRequest)(nil),      // 12: calendar.GetCalendarDataRequest
	(*GetCalendarDataResponse)(nil),     // 13: calendar.GetCalendarDataResponse
	(*GetUserAvailabilityRequest)(nil),  // 14: calendar.GetUserAvailabilityRequest
	(*AvailabilityStatus)(nil),          // 15: calendar.AvailabilityStatus
	(*GetUserAvailabilityResponse)(nil), // 16: calendar.GetUserAvailabilityResponse
	(*QueryEventsRequest)(nil),          // 17: calendar.QueryEventsRequest
	(*QueryEventsResponse)(nil),         // 18: calendar.QueryEventsResponse
}
var file_proto_calendar_calendar_proto_depIdxs = []int32{
	0,  // 0: calendar.CreateEventResponse.event:type_name -> calendar.Event
	0,  // 1: calendar.GetEventsResponse.events:type_name -> calendar.Event
	0,  // 2: calendar.UpdateEventResponse.event:type_name -> calendar.Event
	10, // 3: calendar.GetAvailableSlotsResponse.slots:type_name -> calendar.TimeSlot
	0,  // 4: calendar.GetCalendarDataResponse.events:type_name -> calendar.Event
	0,  // 5: calendar.AvailabilityStatus.conflicting_events:type_name -> calendar.Event
	15, // 6: calendar.GetUserAvailabilityResponse.status:type_name -> calendar.AvailabilityStatus
	0,  // 7: calendar.QueryEventsResponse.events:type_name -> calendar.Event
	1,  // 8: calendar.CalendarService.CreateEvent:input_type -> calendar.CreateEventRequest
	3,  // 9: calendar.CalendarService.GetEvents:input_type -> calendar.GetEventsRequest
	5,  // 10: calendar.CalendarService.UpdateEvent:input_type -> calendar.UpdateEventRequest
	7,  // 11: calendar.CalendarService.DeleteEvent:input_type -> calendar.DeleteEventRequest
	9,  // 12: calendar.CalendarService.GetAvailableSlots:input_type -> calendar.GetAvailableSlotsRequest
	12, // 13: calendar.CalendarDataService.GetCalendarData:input_type -> calendar.GetCalendarDataRequest
	14, // 14: calendar.CalendarDataService.GetUserAvailability:input_type -> calendar.GetUserAvailabilityRequest
	17, // 15: calendar.CalendarDataService.QueryEvents:input_type -> calendar.QueryEventsRequest
	2,  // 16: calendar.CalendarService.CreateEvent:output_type -> calendar.CreateEventResponse
	4,  // 17: calendar.CalendarService.GetEvents:output_type -> calendar.GetEventsResponse
	6,  // 18: calendar.CalendarService.UpdateEvent:output_type -> calendar.UpdateEventResponse
	8,  // 19: calendar.CalendarService.DeleteEvent:output_type -> calendar.DeleteEventResponse
	11, // 20: calendar.CalendarService.GetAvailableSlots:output_type -> calendar.GetAvailableSlotsResponse
	13, // 21: calendar.CalendarDataService.GetCalendarData:output_type -> calendar.GetCalendarDataResponse
	16, // 22: calendar.CalendarDataService.GetUserAvailability:output_type -> calendar.GetUserAvailabilityResponse
	18, // 23: calendar.CalendarDataService.QueryEvents:output_type -> calendar.QueryEventsResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_calendar_calendar_proto_init() }
func file_proto_calendar_calendar_proto_init() {
	if File_proto_calendar_calendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calendar_calendar_proto_rawDesc), len(file_proto_calendar_calendar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_calendar_calendar_proto_goTypes,
		DependencyIndexes: file_proto_calendar_calendar_proto_depIdxs,
		MessageInfos:      file_proto_calendar_calendar_proto_msgTypes,
	}.Build()
	File_proto_calendar_calendar_proto = out.File
	file_proto_calendar_calendar_proto_goTypes = nil
	file_proto_calendar_calendar_proto_depIdxs = nil
}
