// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/calendar/calendar_data.proto

package calendar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CalendarDataService_GetCalendarData_FullMethodName     = "/calendar.CalendarDataService/GetCalendarData"
	CalendarDataService_GetUserAvailability_FullMethodName = "/calendar.CalendarDataService/GetUserAvailability"
	CalendarDataService_QueryEvents_FullMethodName         = "/calendar.CalendarDataService/QueryEvents"
)

// CalendarDataServiceClient is the client API for CalendarDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CalendarDataService defines the gRPC service for Core to expose calendar data to Agent
// Agent calls this service to fetch calendar data while processing user requests
type CalendarDataServiceClient interface {
	// GetCalendarData retrieves calendar events for a given user and time range
	GetCalendarData(ctx context.Context, in *GetCalendarDataRequest, opts ...grpc.CallOption) (*GetCalendarDataResponse, error)
	// GetUserAvailability checks user availability for a specific time slot
	GetUserAvailability(ctx context.Context, in *GetUserAvailabilityRequest, opts ...grpc.CallOption) (*GetUserAvailabilityResponse, error)
	// QueryEvents performs complex queries on calendar events
	QueryEvents(ctx context.Context, in *QueryEventsRequest, opts ...grpc.CallOption) (*QueryEventsResponse, error)
}

type calendarDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalendarDataServiceClient(cc grpc.ClientConnInterface) CalendarDataServiceClient {
	return &calendarDataServiceClient{cc}
}

func (c *calendarDataServiceClient) GetCalendarData(ctx context.Context, in *GetCalendarDataRequest, opts ...grpc.CallOption) (*GetCalendarDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCalendarDataResponse)
	err := c.cc.Invoke(ctx, CalendarDataService_GetCalendarData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarDataServiceClient) GetUserAvailability(ctx context.Context, in *GetUserAvailabilityRequest, opts ...grpc.CallOption) (*GetUserAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAvailabilityResponse)
	err := c.cc.Invoke(ctx, CalendarDataService_GetUserAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarDataServiceClient) QueryEvents(ctx context.Context, in *QueryEventsRequest, opts ...grpc.CallOption) (*QueryEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryEventsResponse)
	err := c.cc.Invoke(ctx, CalendarDataService_QueryEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarDataServiceServer is the server API for CalendarDataService service.
// All implementations must embed UnimplementedCalendarDataServiceServer
// for forward compatibility.
//
// CalendarDataService defines the gRPC service for Core to expose calendar data to Agent
// Agent calls this service to fetch calendar data while processing user requests
type CalendarDataServiceServer interface {
	// GetCalendarData retrieves calendar events for a given user and time range
	GetCalendarData(context.Context, *GetCalendarDataRequest) (*GetCalendarDataResponse, error)
	// GetUserAvailability checks user availability for a specific time slot
	GetUserAvailability(context.Context, *GetUserAvailabilityRequest) (*GetUserAvailabilityResponse, error)
	// QueryEvents performs complex queries on calendar events
	QueryEvents(context.Context, *QueryEventsRequest) (*QueryEventsResponse, error)
	mustEmbedUnimplementedCalendarDataServiceServer()
}

// UnimplementedCalendarDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalendarDataServiceServer struct{}

func (UnimplementedCalendarDataServiceServer) GetCalendarData(context.Context, *GetCalendarDataRequest) (*GetCalendarDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCalendarData not implemented")
}
func (UnimplementedCalendarDataServiceServer) GetUserAvailability(context.Context, *GetUserAvailabilityRequest) (*GetUserAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAvailability not implemented")
}
func (UnimplementedCalendarDataServiceServer) QueryEvents(context.Context, *QueryEventsRequest) (*QueryEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryEvents not implemented")
}
func (UnimplementedCalendarDataServiceServer) mustEmbedUnimplementedCalendarDataServiceServer() {}
func (UnimplementedCalendarDataServiceServer) testEmbeddedByValue()                             {}

// UnsafeCalendarDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalendarDataServiceServer will
// result in compilation errors.
type UnsafeCalendarDataServiceServer interface {
	mustEmbedUnimplementedCalendarDataServiceServer()
}

func RegisterCalendarDataServiceServer(s grpc.ServiceRegistrar, srv CalendarDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedCalendarDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CalendarDataService_ServiceDesc, srv)
}

func _CalendarDataService_GetCalendarData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCalendarDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarDataServiceServer).GetCalendarData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalendarDataService_GetCalendarData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarDataServiceServer).GetCalendarData(ctx, req.(*GetCalendarDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarDataService_GetUserAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarDataServiceServer).GetUserAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalendarDataService_GetUserAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarDataServiceServer).GetUserAvailability(ctx, req.(*GetUserAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarDataService_QueryEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarDataServiceServer).QueryEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalendarDataService_QueryEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarDataServiceServer).QueryEvents(ctx, req.(*QueryEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CalendarDataService_ServiceDesc is the grpc.ServiceDesc for CalendarDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalendarDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calendar.CalendarDataService",
	HandlerType: (*CalendarDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCalendarData",
			Handler:    _CalendarDataService_GetCalendarData_Handler,
		},
		{
			MethodName: "GetUserAvailability",
			Handler:    _CalendarDataService_GetUserAvailability_Handler,
		},
		{
			MethodName: "QueryEvents",
			Handler:    _CalendarDataService_QueryEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/calendar/calendar_data.proto",
}
