// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/calendar/calendar_data.proto

package calendar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCalendarDataRequest is used by Agent to request calendar data from Core
type GetCalendarDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix timestamp
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // Unix timestamp
	Categories    []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`                 // Optional: filter by event categories
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCalendarDataRequest) Reset() {
	*x = GetCalendarDataRequest{}
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCalendarDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCalendarDataRequest) ProtoMessage() {}

func (x *GetCalendarDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCalendarDataRequest.ProtoReflect.Descriptor instead.
func (*GetCalendarDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetCalendarDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCalendarDataRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetCalendarDataRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetCalendarDataRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

// GetCalendarDataResponse contains calendar events from Core
type GetCalendarDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCalendarDataResponse) Reset() {
	*x = GetCalendarDataResponse{}
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCalendarDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCalendarDataResponse) ProtoMessage() {}

func (x *GetCalendarDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCalendarDataResponse.ProtoReflect.Descriptor instead.
func (*GetCalendarDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetCalendarDataResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetCalendarDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCalendarDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetUserAvailabilityRequest checks if a user is available during a time slot
type GetUserAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAvailabilityRequest) Reset() {
	*x = GetUserAvailabilityRequest{}
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAvailabilityRequest) ProtoMessage() {}

func (x *GetUserAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetUserAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_data_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserAvailabilityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserAvailabilityRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetUserAvailabilityRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// AvailabilityStatus represents the availability of a user
type AvailabilityStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Available         bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Reason            string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ConflictingEvents []*Event               `protobuf:"bytes,3,rep,name=conflicting_events,json=conflictingEvents,proto3" json:"conflicting_events,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AvailabilityStatus) Reset() {
	*x = AvailabilityStatus{}
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityStatus) ProtoMessage() {}

func (x *AvailabilityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityStatus.ProtoReflect.Descriptor instead.
func (*AvailabilityStatus) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_data_proto_rawDescGZIP(), []int{3}
}

func (x *AvailabilityStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *AvailabilityStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AvailabilityStatus) GetConflictingEvents() []*Event {
	if x != nil {
		return x.ConflictingEvents
	}
	return nil
}

// GetUserAvailabilityResponse contains availability information
type GetUserAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *AvailabilityStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAvailabilityResponse) Reset() {
	*x = GetUserAvailabilityResponse{}
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAvailabilityResponse) ProtoMessage() {}

func (x *GetUserAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*GetUserAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_data_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserAvailabilityResponse) GetStatus() *AvailabilityStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetUserAvailabilityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserAvailabilityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// QueryEventsRequest allows Agent to perform complex queries on events
type QueryEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"` // Free-form query string (e.g., "meetings with john")
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`   // Optional tags to filter by
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsRequest) Reset() {
	*x = QueryEventsRequest{}
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest) ProtoMessage() {}

func (x *QueryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_data_proto_rawDescGZIP(), []int{5}
}

func (x *QueryEventsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryEventsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryEventsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryEventsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryEventsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// QueryEventsResponse contains results of the query
type QueryEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsResponse) Reset() {
	*x = QueryEventsResponse{}
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse) ProtoMessage() {}

func (x *QueryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_data_proto_rawDescGZIP(), []int{6}
}

func (x *QueryEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryEventsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *QueryEventsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryEventsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_calendar_calendar_data_proto protoreflect.FileDescriptor

const file_proto_calendar_calendar_data_proto_rawDesc = "" +
	"\n" +
	"\"proto/calendar/calendar_data.proto\x12\bcalendar\x1a\x1dproto/calendar/calendar.proto\"\x8b\x01\n" +
	"\x16GetCalendarDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\"v\n" +
	"\x17GetCalendarDataResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"o\n" +
	"\x1aGetUserAvailabilityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\"\x8a\x01\n" +
	"\x12AvailabilityStatus\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12>\n" +
	"\x12conflicting_events\x18\x03 \x03(\v2\x0f.calendar.EventR\x11conflictingEvents\"\x87\x01\n" +
	"\x1bGetUserAvailabilityResponse\x124\n" +
	"\x06status\x18\x01 \x01(\v2\x1c.calendar.AvailabilityStatusR\x06status\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x91\x01\n" +
	"\x12QueryEventsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"\x93\x01\n" +
	"\x13QueryEventsResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\x9d\x02\n" +
	"\x13CalendarDataService\x12V\n" +
	"\x0fGetCalendarData\x12 .calendar.GetCalendarDataRequest\x1a!.calendar.GetCalendarDataResponse\x12b\n" +
	"\x13GetUserAvailability\x12$.calendar.GetUserAvailabilityRequest\x1a%.calendar.GetUserAvailabilityResponse\x12J\n" +
	"\vQueryEvents\x12\x1c.calendar.QueryEventsRequest\x1a\x1d.calendar.QueryEventsResponseB-Z+github.com/waydxd/Orbit-core/proto/calendarb\x06proto3"

var (
	file_proto_calendar_calendar_data_proto_rawDescOnce sync.Once
	file_proto_calendar_calendar_data_proto_rawDescData []byte
)

func file_proto_calendar_calendar_data_proto_rawDescGZIP() []byte {
	file_proto_calendar_calendar_data_proto_rawDescOnce.Do(func() {
		file_proto_calendar_calendar_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calendar_calendar_data_proto_rawDesc), len(file_proto_calendar_calendar_data_proto_rawDesc)))
	})
	return file_proto_calendar_calendar_data_proto_rawDescData
}

var file_proto_calendar_calendar_data_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_calendar_calendar_data_proto_goTypes = []any{
	(*GetCalendarDataRequest)(nil),      // 0: calendar.GetCalendarDataRequest
	(*GetCalendarDataResponse)(nil),     // 1: calendar.GetCalendarDataResponse
	(*GetUserAvailabilityRequest)(nil),  // 2: calendar.GetUserAvailabilityRequest
	(*AvailabilityStatus)(nil),          // 3: calendar.AvailabilityStatus
	(*GetUserAvailabilityResponse)(nil), // 4: calendar.GetUserAvailabilityResponse
	(*QueryEventsRequest)(nil),          // 5: calendar.QueryEventsRequest
	(*QueryEventsResponse)(nil),         // 6: calendar.QueryEventsResponse
	(*Event)(nil),                       // 7: calendar.Event
}
var file_proto_calendar_calendar_data_proto_depIdxs = []int32{
	7, // 0: calendar.GetCalendarDataResponse.events:type_name -> calendar.Event
	7, // 1: calendar.AvailabilityStatus.conflicting_events:type_name -> calendar.Event
	3, // 2: calendar.GetUserAvailabilityResponse.status:type_name -> calendar.AvailabilityStatus
	7, // 3: calendar.QueryEventsResponse.events:type_name -> calendar.Event
	0, // 4: calendar.CalendarDataService.GetCalendarData:input_type -> calendar.GetCalendarDataRequest
	2, // 5: calendar.CalendarDataService.GetUserAvailability:input_type -> calendar.GetUserAvailabilityRequest
	5, // 6: calendar.CalendarDataService.QueryEvents:input_type -> calendar.QueryEventsRequest
	1, // 7: calendar.CalendarDataService.GetCalendarData:output_type -> calendar.GetCalendarDataResponse
	4, // 8: calendar.CalendarDataService.GetUserAvailability:output_type -> calendar.GetUserAvailabilityResponse
	6, // 9: calendar.CalendarDataService.QueryEvents:output_type -> calendar.QueryEventsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_calendar_calendar_data_proto_init() }
func file_proto_calendar_calendar_data_proto_init() {
	if File_proto_calendar_calendar_data_proto != nil {
		return
	}
	file_proto_calendar_calendar_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calendar_calendar_data_proto_rawDesc), len(file_proto_calendar_calendar_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calendar_calendar_data_proto_goTypes,
		DependencyIndexes: file_proto_calendar_calendar_data_proto_depIdxs,
		MessageInfos:      file_proto_calendar_calendar_data_proto_msgTypes,
	}.Build()
	File_proto_calendar_calendar_data_proto = out.File
	file_proto_calendar_calendar_data_proto_goTypes = nil
	file_proto_calendar_calendar_data_proto_depIdxs = nil
}
