// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token_hash, expires_at, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, CURRENT_TIMESTAMP)
RETURNING id
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, password_hash, first_name, last_name, email_verified, username, profile_picture, region, timezone, gender, birth_date, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateUserParams struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	FirstName      pgtype.Text        `json:"first_name"`
	LastName       pgtype.Text        `json:"last_name"`
	EmailVerified  bool               `json:"email_verified"`
	Username       pgtype.Text        `json:"username"`
	ProfilePicture pgtype.Text        `json:"profile_picture"`
	Region         pgtype.Text        `json:"region"`
	Timezone       pgtype.Text        `json:"timezone"`
	Gender         pgtype.Text        `json:"gender"`
	BirthDate      pgtype.Date        `json:"birth_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.EmailVerified,
		arg.Username,
		arg.ProfilePicture,
		arg.Region,
		arg.Timezone,
		arg.Gender,
		arg.BirthDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, token_hash, expires_at, created_at
FROM sessions WHERE token_hash = $1 AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetSessionByToken(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, email_verified, username, profile_picture, region, timezone, gender, birth_date, created_at, updated_at
FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	FirstName      pgtype.Text        `json:"first_name"`
	LastName       pgtype.Text        `json:"last_name"`
	EmailVerified  bool               `json:"email_verified"`
	Username       pgtype.Text        `json:"username"`
	ProfilePicture pgtype.Text        `json:"profile_picture"`
	Region         pgtype.Text        `json:"region"`
	Timezone       pgtype.Text        `json:"timezone"`
	Gender         pgtype.Text        `json:"gender"`
	BirthDate      pgtype.Date        `json:"birth_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.EmailVerified,
		&i.Username,
		&i.ProfilePicture,
		&i.Region,
		&i.Timezone,
		&i.Gender,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, first_name, last_name, email_verified, username, profile_picture, region, timezone, gender, birth_date, created_at, updated_at
FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	FirstName      pgtype.Text        `json:"first_name"`
	LastName       pgtype.Text        `json:"last_name"`
	EmailVerified  bool               `json:"email_verified"`
	Username       pgtype.Text        `json:"username"`
	ProfilePicture pgtype.Text        `json:"profile_picture"`
	Region         pgtype.Text        `json:"region"`
	Timezone       pgtype.Text        `json:"timezone"`
	Gender         pgtype.Text        `json:"gender"`
	BirthDate      pgtype.Date        `json:"birth_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.EmailVerified,
		&i.Username,
		&i.ProfilePicture,
		&i.Region,
		&i.Timezone,
		&i.Gender,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, password_hash, first_name, last_name, email_verified, username, profile_picture, region, timezone, gender, birth_date, created_at, updated_at
FROM users WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	FirstName      pgtype.Text        `json:"first_name"`
	LastName       pgtype.Text        `json:"last_name"`
	EmailVerified  bool               `json:"email_verified"`
	Username       pgtype.Text        `json:"username"`
	ProfilePicture pgtype.Text        `json:"profile_picture"`
	Region         pgtype.Text        `json:"region"`
	Timezone       pgtype.Text        `json:"timezone"`
	Gender         pgtype.Text        `json:"gender"`
	BirthDate      pgtype.Date        `json:"birth_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username pgtype.Text) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.EmailVerified,
		&i.Username,
		&i.ProfilePicture,
		&i.Region,
		&i.Timezone,
		&i.Gender,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = $1, password_hash = $2, first_name = $3, last_name = $4, email_verified = $5, username = $6, profile_picture = $7, region = $8, timezone = $9, gender = $10, birth_date = $11, updated_at = $12
WHERE id = $13
`

type UpdateUserParams struct {
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	FirstName      pgtype.Text        `json:"first_name"`
	LastName       pgtype.Text        `json:"last_name"`
	EmailVerified  bool               `json:"email_verified"`
	Username       pgtype.Text        `json:"username"`
	ProfilePicture pgtype.Text        `json:"profile_picture"`
	Region         pgtype.Text        `json:"region"`
	Timezone       pgtype.Text        `json:"timezone"`
	Gender         pgtype.Text        `json:"gender"`
	BirthDate      pgtype.Date        `json:"birth_date"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.EmailVerified,
		arg.Username,
		arg.ProfilePicture,
		arg.Region,
		arg.Timezone,
		arg.Gender,
		arg.BirthDate,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
