// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (id, user_id, title, description, start_time, end_time, location, is_recurring, recurrence_rule, recurrence_exception, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateEventParams struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	EndTime             pgtype.Timestamptz `json:"end_time"`
	Location            pgtype.Text        `json:"location"`
	IsRecurring         pgtype.Bool        `json:"is_recurring"`
	RecurrenceRule      pgtype.Text        `json:"recurrence_rule"`
	RecurrenceException pgtype.Text        `json:"recurrence_exception"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.IsRecurring,
		arg.RecurrenceRule,
		arg.RecurrenceException,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (id, user_id, title, description, due_date, completed, priority, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateTaskParams struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Completed   pgtype.Bool        `json:"completed"`
	Priority    pgtype.Text        `json:"priority"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.Exec(ctx, createTask,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.Completed,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, user_id, title, description, start_time, end_time, location, is_recurring, recurrence_rule, recurrence_exception, created_at, updated_at
FROM events WHERE id = $1
`

type GetEventByIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	EndTime             pgtype.Timestamptz `json:"end_time"`
	Location            pgtype.Text        `json:"location"`
	IsRecurring         pgtype.Bool        `json:"is_recurring"`
	RecurrenceRule      pgtype.Text        `json:"recurrence_rule"`
	RecurrenceException pgtype.Text        `json:"recurrence_exception"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (GetEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.IsRecurring,
		&i.RecurrenceRule,
		&i.RecurrenceException,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, user_id, title, description, due_date, completed, priority, created_at, updated_at
FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.Completed,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsByTime = `-- name: ListEventsByTime :many
SELECT e.id, e.user_id, e.title, e.description, e.start_time, e.end_time, e.location, e.is_recurring, e.recurrence_rule, e.recurrence_exception, e.created_at, e.updated_at
FROM events e
WHERE e.start_time <= $1 AND e.end_time >= $2
UNION
SELECT e.id, e.user_id, e.title, e.description, e.start_time, e.end_time, e.location, e.is_recurring, e.recurrence_rule, e.recurrence_exception, e.created_at, e.updated_at
FROM events e
WHERE e.is_recurring = true
  AND e.start_time <= $1
ORDER BY start_time
`

type ListEventsByTimeParams struct {
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
}

type ListEventsByTimeRow struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	EndTime             pgtype.Timestamptz `json:"end_time"`
	Location            pgtype.Text        `json:"location"`
	IsRecurring         pgtype.Bool        `json:"is_recurring"`
	RecurrenceRule      pgtype.Text        `json:"recurrence_rule"`
	RecurrenceException pgtype.Text        `json:"recurrence_exception"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEventsByTime(ctx context.Context, arg ListEventsByTimeParams) ([]ListEventsByTimeRow, error) {
	rows, err := q.db.Query(ctx, listEventsByTime, arg.WindowEnd, arg.WindowStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsByTimeRow
	for rows.Next() {
		var i ListEventsByTimeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.RecurrenceException,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByUserAndTime = `-- name: ListEventsByUserAndTime :many
SELECT e.id, e.user_id, e.title, e.description, e.start_time, e.end_time, e.location, e.is_recurring, e.recurrence_rule, e.recurrence_exception, e.created_at, e.updated_at
FROM events e
WHERE e.user_id = $1
  AND e.start_time <= $2 AND e.end_time >= $3
UNION
SELECT e.id, e.user_id, e.title, e.description, e.start_time, e.end_time, e.location, e.is_recurring, e.recurrence_rule, e.recurrence_exception, e.created_at, e.updated_at
FROM events e
WHERE e.user_id = $1
  AND e.is_recurring = true
  AND e.start_time <= $2
ORDER BY start_time
`

type ListEventsByUserAndTimeParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
}

type ListEventsByUserAndTimeRow struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	EndTime             pgtype.Timestamptz `json:"end_time"`
	Location            pgtype.Text        `json:"location"`
	IsRecurring         pgtype.Bool        `json:"is_recurring"`
	RecurrenceRule      pgtype.Text        `json:"recurrence_rule"`
	RecurrenceException pgtype.Text        `json:"recurrence_exception"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEventsByUserAndTime(ctx context.Context, arg ListEventsByUserAndTimeParams) ([]ListEventsByUserAndTimeRow, error) {
	rows, err := q.db.Query(ctx, listEventsByUserAndTime, arg.UserID, arg.WindowEnd, arg.WindowStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsByUserAndTimeRow
	for rows.Next() {
		var i ListEventsByUserAndTimeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.RecurrenceException,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, user_id, title, description, due_date, completed, priority, created_at, updated_at
FROM tasks
WHERE user_id = $1
  AND ($2::boolean IS NULL OR completed = $2)
ORDER BY due_date ASC
`

type ListTasksParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Completed pgtype.Bool `json:"completed"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.UserID, arg.Completed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.Completed,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events
SET title = $1, description = $2, start_time = $3, end_time = $4, location = $5, is_recurring = $6, recurrence_rule = $7, recurrence_exception = $8, updated_at = $9
WHERE id = $10
`

type UpdateEventParams struct {
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	EndTime             pgtype.Timestamptz `json:"end_time"`
	Location            pgtype.Text        `json:"location"`
	IsRecurring         pgtype.Bool        `json:"is_recurring"`
	RecurrenceRule      pgtype.Text        `json:"recurrence_rule"`
	RecurrenceException pgtype.Text        `json:"recurrence_exception"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ID                  pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.Exec(ctx, updateEvent,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.IsRecurring,
		arg.RecurrenceRule,
		arg.RecurrenceException,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET title = $1, description = $2, due_date = $3, completed = $4, priority = $5, updated_at = $6
WHERE id = $7
`

type UpdateTaskParams struct {
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Completed   pgtype.Bool        `json:"completed"`
	Priority    pgtype.Text        `json:"priority"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.Completed,
		arg.Priority,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
