// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHabitSuggestion = `-- name: CreateHabitSuggestion :exec
INSERT INTO habit_suggestions (
    id, user_id, event_frequency_id, title, description, location,
    duration_minutes, time_of_day, day_of_week, status, created_at, updated_at, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateHabitSuggestionParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	EventFrequencyID pgtype.UUID        `json:"event_frequency_id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Location         pgtype.Text        `json:"location"`
	DurationMinutes  int32              `json:"duration_minutes"`
	TimeOfDay        int32              `json:"time_of_day"`
	DayOfWeek        int32              `json:"day_of_week"`
	Status           pgtype.Text        `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateHabitSuggestion(ctx context.Context, arg CreateHabitSuggestionParams) error {
	_, err := q.db.Exec(ctx, createHabitSuggestion,
		arg.ID,
		arg.UserID,
		arg.EventFrequencyID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.DurationMinutes,
		arg.TimeOfDay,
		arg.DayOfWeek,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createRecurringEvent = `-- name: CreateRecurringEvent :exec
INSERT INTO events (
    id, user_id, title, description, location,
    start_time, end_time, is_recurring, recurrence_rule, recurrence_exception, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateRecurringEventParams struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	Location            pgtype.Text        `json:"location"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	EndTime             pgtype.Timestamptz `json:"end_time"`
	IsRecurring         pgtype.Bool        `json:"is_recurring"`
	RecurrenceRule      pgtype.Text        `json:"recurrence_rule"`
	RecurrenceException pgtype.Text        `json:"recurrence_exception"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateRecurringEvent(ctx context.Context, arg CreateRecurringEventParams) error {
	_, err := q.db.Exec(ctx, createRecurringEvent,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.IsRecurring,
		arg.RecurrenceRule,
		arg.RecurrenceException,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deactivateRecurringEvent = `-- name: DeactivateRecurringEvent :exec
UPDATE events
SET is_recurring = FALSE, updated_at = $1
WHERE id = $2
`

type DeactivateRecurringEventParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) DeactivateRecurringEvent(ctx context.Context, arg DeactivateRecurringEventParams) error {
	_, err := q.db.Exec(ctx, deactivateRecurringEvent, arg.UpdatedAt, arg.ID)
	return err
}

const getActiveRecurringEvents = `-- name: GetActiveRecurringEvents :many
SELECT id, user_id, title, description, location, hashtag,
       start_time, end_time, is_recurring, recurrence_rule, recurrence_exception,
       created_at, updated_at
FROM events
WHERE user_id = $1 AND is_recurring = TRUE
ORDER BY created_at DESC
`

type GetActiveRecurringEventsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	Location            pgtype.Text        `json:"location"`
	Hashtag             pgtype.Text        `json:"hashtag"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	EndTime             pgtype.Timestamptz `json:"end_time"`
	IsRecurring         pgtype.Bool        `json:"is_recurring"`
	RecurrenceRule      pgtype.Text        `json:"recurrence_rule"`
	RecurrenceException pgtype.Text        `json:"recurrence_exception"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActiveRecurringEvents(ctx context.Context, userID pgtype.UUID) ([]GetActiveRecurringEventsRow, error) {
	rows, err := q.db.Query(ctx, getActiveRecurringEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveRecurringEventsRow
	for rows.Next() {
		var i GetActiveRecurringEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Hashtag,
			&i.StartTime,
			&i.EndTime,
			&i.IsRecurring,
			&i.RecurrenceRule,
			&i.RecurrenceException,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventFrequenciesAboveThreshold = `-- name: GetEventFrequenciesAboveThreshold :many
SELECT id, user_id, title, description, location, duration_minutes,
       time_of_day, day_of_week, occurrence_count, suggestion_threshold,
       suggestion_shown, habit_accepted, occurrence_timestamps, created_at, updated_at
FROM event_frequency
WHERE user_id = $1 AND occurrence_count >= $2 AND suggestion_shown = FALSE AND habit_accepted = FALSE
ORDER BY occurrence_count DESC
`

type GetEventFrequenciesAboveThresholdParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	OccurrenceCount int32       `json:"occurrence_count"`
}

func (q *Queries) GetEventFrequenciesAboveThreshold(ctx context.Context, arg GetEventFrequenciesAboveThresholdParams) ([]EventFrequency, error) {
	rows, err := q.db.Query(ctx, getEventFrequenciesAboveThreshold, arg.UserID, arg.OccurrenceCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventFrequency
	for rows.Next() {
		var i EventFrequency
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.DurationMinutes,
			&i.TimeOfDay,
			&i.DayOfWeek,
			&i.OccurrenceCount,
			&i.SuggestionThreshold,
			&i.SuggestionShown,
			&i.HabitAccepted,
			&i.OccurrenceTimestamps,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventFrequencyByPattern = `-- name: GetEventFrequencyByPattern :one
SELECT id, user_id, title, description, location, duration_minutes,
       time_of_day, day_of_week, occurrence_count, suggestion_threshold,
       suggestion_shown, habit_accepted, occurrence_timestamps, created_at, updated_at
FROM event_frequency
WHERE user_id = $1 AND title = $2 AND duration_minutes = $3
      AND time_of_day = $4 AND day_of_week = $5
`

type GetEventFrequencyByPatternParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	Title           string      `json:"title"`
	DurationMinutes int32       `json:"duration_minutes"`
	TimeOfDay       int32       `json:"time_of_day"`
	DayOfWeek       pgtype.Int4 `json:"day_of_week"`
}

func (q *Queries) GetEventFrequencyByPattern(ctx context.Context, arg GetEventFrequencyByPatternParams) (EventFrequency, error) {
	row := q.db.QueryRow(ctx, getEventFrequencyByPattern,
		arg.UserID,
		arg.Title,
		arg.DurationMinutes,
		arg.TimeOfDay,
		arg.DayOfWeek,
	)
	var i EventFrequency
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.DurationMinutes,
		&i.TimeOfDay,
		&i.DayOfWeek,
		&i.OccurrenceCount,
		&i.SuggestionThreshold,
		&i.SuggestionShown,
		&i.HabitAccepted,
		&i.OccurrenceTimestamps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHabitSuggestionByID = `-- name: GetHabitSuggestionByID :one
SELECT id, user_id, event_frequency_id, title, description, location,
       duration_minutes, time_of_day, day_of_week, status,
       recurrence_end_date, created_at, updated_at, expires_at
FROM habit_suggestions
WHERE id = $1
`

func (q *Queries) GetHabitSuggestionByID(ctx context.Context, id pgtype.UUID) (HabitSuggestion, error) {
	row := q.db.QueryRow(ctx, getHabitSuggestionByID, id)
	var i HabitSuggestion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventFrequencyID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.DurationMinutes,
		&i.TimeOfDay,
		&i.DayOfWeek,
		&i.Status,
		&i.RecurrenceEndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPendingHabitSuggestions = `-- name: GetPendingHabitSuggestions :many
SELECT id, user_id, event_frequency_id, title, description, location,
       duration_minutes, time_of_day, day_of_week, status,
       recurrence_end_date, created_at, updated_at, expires_at
FROM habit_suggestions
WHERE user_id = $1 AND status = 'pending' AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) GetPendingHabitSuggestions(ctx context.Context, userID pgtype.UUID) ([]HabitSuggestion, error) {
	rows, err := q.db.Query(ctx, getPendingHabitSuggestions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HabitSuggestion
	for rows.Next() {
		var i HabitSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventFrequencyID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.DurationMinutes,
			&i.TimeOfDay,
			&i.DayOfWeek,
			&i.Status,
			&i.RecurrenceEndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventFrequency = `-- name: UpdateEventFrequency :exec
UPDATE event_frequency
SET occurrence_count = $1, suggestion_shown = $2, habit_accepted = $3,
    occurrence_timestamps = $4, updated_at = $5
WHERE id = $6
`

type UpdateEventFrequencyParams struct {
	OccurrenceCount      int32              `json:"occurrence_count"`
	SuggestionShown      bool               `json:"suggestion_shown"`
	HabitAccepted        bool               `json:"habit_accepted"`
	OccurrenceTimestamps []byte             `json:"occurrence_timestamps"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ID                   pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateEventFrequency(ctx context.Context, arg UpdateEventFrequencyParams) error {
	_, err := q.db.Exec(ctx, updateEventFrequency,
		arg.OccurrenceCount,
		arg.SuggestionShown,
		arg.HabitAccepted,
		arg.OccurrenceTimestamps,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateHabitSuggestionStatus = `-- name: UpdateHabitSuggestionStatus :exec
UPDATE habit_suggestions
SET status = $1, recurrence_end_date = $2, updated_at = $3
WHERE id = $4
`

type UpdateHabitSuggestionStatusParams struct {
	Status            pgtype.Text        `json:"status"`
	RecurrenceEndDate pgtype.Timestamptz `json:"recurrence_end_date"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ID                pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateHabitSuggestionStatus(ctx context.Context, arg UpdateHabitSuggestionStatusParams) error {
	_, err := q.db.Exec(ctx, updateHabitSuggestionStatus,
		arg.Status,
		arg.RecurrenceEndDate,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertEventFrequency = `-- name: UpsertEventFrequency :one
INSERT INTO event_frequency (
    id, user_id, title, description, location, duration_minutes,
    time_of_day, day_of_week, occurrence_count, suggestion_threshold,
    suggestion_shown, habit_accepted, occurrence_timestamps, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (user_id, title, duration_minutes, time_of_day, day_of_week)
DO UPDATE SET
    occurrence_count = event_frequency.occurrence_count + 1,
    occurrence_timestamps = $13,
    updated_at = $15
RETURNING id, occurrence_count
`

type UpsertEventFrequencyParams struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	Location             pgtype.Text        `json:"location"`
	DurationMinutes      int32              `json:"duration_minutes"`
	TimeOfDay            int32              `json:"time_of_day"`
	DayOfWeek            pgtype.Int4        `json:"day_of_week"`
	OccurrenceCount      int32              `json:"occurrence_count"`
	SuggestionThreshold  int32              `json:"suggestion_threshold"`
	SuggestionShown      bool               `json:"suggestion_shown"`
	HabitAccepted        bool               `json:"habit_accepted"`
	OccurrenceTimestamps []byte             `json:"occurrence_timestamps"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type UpsertEventFrequencyRow struct {
	ID              pgtype.UUID `json:"id"`
	OccurrenceCount int32       `json:"occurrence_count"`
}

func (q *Queries) UpsertEventFrequency(ctx context.Context, arg UpsertEventFrequencyParams) (UpsertEventFrequencyRow, error) {
	row := q.db.QueryRow(ctx, upsertEventFrequency,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.DurationMinutes,
		arg.TimeOfDay,
		arg.DayOfWeek,
		arg.OccurrenceCount,
		arg.SuggestionThreshold,
		arg.SuggestionShown,
		arg.HabitAccepted,
		arg.OccurrenceTimestamps,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UpsertEventFrequencyRow
	err := row.Scan(&i.ID, &i.OccurrenceCount)
	return i, err
}
