// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: integration.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIntegration = `-- name: CreateIntegration :exec
INSERT INTO integrations (id, user_id, service_name, api_key_encrypted, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateIntegrationParams struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ServiceName     string             `json:"service_name"`
	ApiKeyEncrypted string             `json:"api_key_encrypted"`
	Status          pgtype.Text        `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) error {
	_, err := q.db.Exec(ctx, createIntegration,
		arg.ID,
		arg.UserID,
		arg.ServiceName,
		arg.ApiKeyEncrypted,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integrations WHERE id = $1
`

func (q *Queries) DeleteIntegration(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIntegration, id)
	return err
}

const getIntegrationByID = `-- name: GetIntegrationByID :one
SELECT id, user_id, service_name, api_key_encrypted, status, last_sync, created_at, updated_at
FROM integrations WHERE id = $1
`

func (q *Queries) GetIntegrationByID(ctx context.Context, id pgtype.UUID) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByID, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationByService = `-- name: GetIntegrationByService :one
SELECT id, user_id, service_name, api_key_encrypted, status, last_sync, created_at, updated_at
FROM integrations WHERE user_id = $1 AND service_name = $2
`

type GetIntegrationByServiceParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ServiceName string      `json:"service_name"`
}

func (q *Queries) GetIntegrationByService(ctx context.Context, arg GetIntegrationByServiceParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByService, arg.UserID, arg.ServiceName)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.ApiKeyEncrypted,
		&i.Status,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, user_id, service_name, api_key_encrypted, status, last_sync, created_at, updated_at
FROM integrations
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListIntegrations(ctx context.Context, userID pgtype.UUID) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Integration
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceName,
			&i.ApiKeyEncrypted,
			&i.Status,
			&i.LastSync,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegration = `-- name: UpdateIntegration :exec
UPDATE integrations
SET service_name = $1, api_key_encrypted = $2, status = $3, updated_at = $4
WHERE id = $5
`

type UpdateIntegrationParams struct {
	ServiceName     string             `json:"service_name"`
	ApiKeyEncrypted string             `json:"api_key_encrypted"`
	Status          pgtype.Text        `json:"status"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ID              pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) error {
	_, err := q.db.Exec(ctx, updateIntegration,
		arg.ServiceName,
		arg.ApiKeyEncrypted,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateLastSync = `-- name: UpdateLastSync :exec
UPDATE integrations
SET last_sync = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateLastSync(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastSync, id)
	return err
}
