// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: location.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :exec
INSERT INTO locations (id, user_id, latitude, longitude, address, timestamp, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateLocationParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Latitude  pgtype.Numeric     `json:"latitude"`
	Longitude pgtype.Numeric     `json:"longitude"`
	Address   pgtype.Text        `json:"address"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) error {
	_, err := q.db.Exec(ctx, createLocation,
		arg.ID,
		arg.UserID,
		arg.Latitude,
		arg.Longitude,
		arg.Address,
		arg.Timestamp,
		arg.CreatedAt,
	)
	return err
}

const findNearby = `-- name: FindNearby :many
SELECT id, user_id, latitude, longitude, address, timestamp, created_at
FROM locations
WHERE ACOS(
    SIN(RADIANS(latitude)) * SIN(RADIANS($1::float8)) +
    COS(RADIANS(latitude)) * COS(RADIANS($1::float8)) * COS(RADIANS(longitude - $2::float8))
) * 6371 <= $3::float8
ORDER BY timestamp DESC
LIMIT 100
`

type FindNearbyParams struct {
	Targetlat float64 `json:"targetlat"`
	Targetlon float64 `json:"targetlon"`
	Radius    float64 `json:"radius"`
}

func (q *Queries) FindNearby(ctx context.Context, arg FindNearbyParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, findNearby, arg.Targetlat, arg.Targetlon, arg.Radius)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Latitude,
			&i.Longitude,
			&i.Address,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentLocation = `-- name: GetCurrentLocation :one
SELECT id, user_id, latitude, longitude, address, timestamp, created_at
FROM locations
WHERE user_id = $1
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetCurrentLocation(ctx context.Context, userID pgtype.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getCurrentLocation, userID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Latitude,
		&i.Longitude,
		&i.Address,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, user_id, latitude, longitude, address, timestamp, created_at
FROM locations WHERE id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, id pgtype.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Latitude,
		&i.Longitude,
		&i.Address,
		&i.Timestamp,
		&i.CreatedAt,
	)
	return i, err
}

const getLocationHistory = `-- name: GetLocationHistory :many
SELECT id, user_id, latitude, longitude, address, timestamp, created_at
FROM locations
WHERE user_id = $1
ORDER BY timestamp DESC
LIMIT $2
`

type GetLocationHistoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetLocationHistory(ctx context.Context, arg GetLocationHistoryParams) ([]Location, error) {
	rows, err := q.db.Query(ctx, getLocationHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Latitude,
			&i.Longitude,
			&i.Address,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
