// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Title               string             `json:"title"`
	Description         pgtype.Text        `json:"description"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	EndTime             pgtype.Timestamptz `json:"end_time"`
	Location            pgtype.Text        `json:"location"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	IsRecurring         pgtype.Bool        `json:"is_recurring"`
	RecurrenceRule      pgtype.Text        `json:"recurrence_rule"`
	RecurrenceException pgtype.Text        `json:"recurrence_exception"`
}

type Integration struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ServiceName     string             `json:"service_name"`
	ApiKeyEncrypted string             `json:"api_key_encrypted"`
	Status          pgtype.Text        `json:"status"`
	LastSync        pgtype.Timestamptz `json:"last_sync"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Location struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Latitude  pgtype.Numeric     `json:"latitude"`
	Longitude pgtype.Numeric     `json:"longitude"`
	Address   pgtype.Text        `json:"address"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Completed   pgtype.Bool        `json:"completed"`
	Priority    pgtype.Text        `json:"priority"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	FirstName      pgtype.Text        `json:"first_name"`
	LastName       pgtype.Text        `json:"last_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	EmailVerified  bool               `json:"email_verified"`
	Username       pgtype.Text        `json:"username"`
	ProfilePicture pgtype.Text        `json:"profile_picture"`
	Region         pgtype.Text        `json:"region"`
	Timezone       pgtype.Text        `json:"timezone"`
	Gender         pgtype.Text        `json:"gender"`
	BirthDate      pgtype.Date        `json:"birth_date"`
}
