// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO event_subscriptions (user_id, event_id, trigger_time, is_sent, status)
VALUES ($1, $2, $3, false, 'pending')
ON CONFLICT ON CONSTRAINT idx_event_subscriptions_user_event_active
DO NOTHING
RETURNING id
`

type CreateSubscriptionParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	EventID     pgtype.UUID        `json:"event_id"`
	TriggerTime pgtype.Timestamptz `json:"trigger_time"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.UserID, arg.EventID, arg.TriggerTime)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE token = $1
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, token)
	return err
}

const deleteDeviceTokenByUser = `-- name: DeleteDeviceTokenByUser :exec
DELETE FROM device_tokens WHERE user_id = $1 AND token = $2
`

type DeleteDeviceTokenByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Token  string      `json:"token"`
}

func (q *Queries) DeleteDeviceTokenByUser(ctx context.Context, arg DeleteDeviceTokenByUserParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceTokenByUser, arg.UserID, arg.Token)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM event_subscriptions
WHERE user_id = $1 AND event_id = $2 AND is_sent = false
`

type DeleteSubscriptionParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	EventID pgtype.UUID `json:"event_id"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteSubscription, arg.UserID, arg.EventID)
	return err
}

const getDeviceTokensByUserID = `-- name: GetDeviceTokensByUserID :many
SELECT id, user_id, token, platform, updated_at
FROM device_tokens
WHERE user_id = $1
`

func (q *Queries) GetDeviceTokensByUserID(ctx context.Context, userID pgtype.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, getDeviceTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, event_id, trigger_time, is_sent, job_id, status, created_at
FROM event_subscriptions
WHERE id = $1
`

type GetSubscriptionByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	EventID     pgtype.UUID        `json:"event_id"`
	TriggerTime pgtype.Timestamptz `json:"trigger_time"`
	IsSent      bool               `json:"is_sent"`
	JobID       pgtype.Text        `json:"job_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSubscriptionByID(ctx context.Context, id pgtype.UUID) (GetSubscriptionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i GetSubscriptionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TriggerTime,
		&i.IsSent,
		&i.JobID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByUserAndEvent = `-- name: GetSubscriptionByUserAndEvent :one
SELECT id, user_id, event_id, trigger_time, is_sent, job_id, status, created_at
FROM event_subscriptions
WHERE user_id = $1 AND event_id = $2 AND status NOT IN ('cancelled', 'sent')
ORDER BY created_at DESC
LIMIT 1
`

type GetSubscriptionByUserAndEventParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	EventID pgtype.UUID `json:"event_id"`
}

type GetSubscriptionByUserAndEventRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	EventID     pgtype.UUID        `json:"event_id"`
	TriggerTime pgtype.Timestamptz `json:"trigger_time"`
	IsSent      bool               `json:"is_sent"`
	JobID       pgtype.Text        `json:"job_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSubscriptionByUserAndEvent(ctx context.Context, arg GetSubscriptionByUserAndEventParams) (GetSubscriptionByUserAndEventRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserAndEvent, arg.UserID, arg.EventID)
	var i GetSubscriptionByUserAndEventRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.TriggerTime,
		&i.IsSent,
		&i.JobID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionsByEventID = `-- name: GetSubscriptionsByEventID :many
SELECT id, user_id, event_id, trigger_time, is_sent, job_id, status, created_at
FROM event_subscriptions
WHERE event_id = $1 AND status NOT IN ('cancelled', 'sent')
`

type GetSubscriptionsByEventIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	EventID     pgtype.UUID        `json:"event_id"`
	TriggerTime pgtype.Timestamptz `json:"trigger_time"`
	IsSent      bool               `json:"is_sent"`
	JobID       pgtype.Text        `json:"job_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSubscriptionsByEventID(ctx context.Context, eventID pgtype.UUID) ([]GetSubscriptionsByEventIDRow, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubscriptionsByEventIDRow
	for rows.Next() {
		var i GetSubscriptionsByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.TriggerTime,
			&i.IsSent,
			&i.JobID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriptionStatus = `-- name: MarkSubscriptionStatus :exec
UPDATE event_subscriptions
SET status = $2, is_sent = $3
WHERE id = $1 AND status = 'pending'
`

type MarkSubscriptionStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
	IsSent bool        `json:"is_sent"`
}

func (q *Queries) MarkSubscriptionStatus(ctx context.Context, arg MarkSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, markSubscriptionStatus, arg.ID, arg.Status, arg.IsSent)
	return err
}

const subscriptionExists = `-- name: SubscriptionExists :one
SELECT EXISTS(
  SELECT 1 FROM event_subscriptions
  WHERE user_id = $1 AND event_id = $2 AND status NOT IN ('cancelled', 'sent', 'failed')
)
`

type SubscriptionExistsParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	EventID pgtype.UUID `json:"event_id"`
}

func (q *Queries) SubscriptionExists(ctx context.Context, arg SubscriptionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, subscriptionExists, arg.UserID, arg.EventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSubscriptionJobID = `-- name: UpdateSubscriptionJobID :exec
UPDATE event_subscriptions SET job_id = $2 WHERE id = $1
`

type UpdateSubscriptionJobIDParams struct {
	ID    pgtype.UUID `json:"id"`
	JobID pgtype.Text `json:"job_id"`
}

func (q *Queries) UpdateSubscriptionJobID(ctx context.Context, arg UpdateSubscriptionJobIDParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionJobID, arg.ID, arg.JobID)
	return err
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec
INSERT INTO device_tokens (user_id, token, platform, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (token) DO UPDATE
  SET user_id = EXCLUDED.user_id,
      platform = EXCLUDED.platform,
      updated_at = NOW()
`

type UpsertDeviceTokenParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Token    string      `json:"token"`
	Platform string      `json:"platform"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceToken, arg.UserID, arg.Token, arg.Platform)
	return err
}
