// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	CreateIntegration(ctx context.Context, arg CreateIntegrationParams) error
	CreateLocation(ctx context.Context, arg CreateLocationParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteEvent(ctx context.Context, id pgtype.UUID) error
	DeleteIntegration(ctx context.Context, id pgtype.UUID) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteTask(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	FindNearby(ctx context.Context, arg FindNearbyParams) ([]Location, error)
	GetCurrentLocation(ctx context.Context, userID pgtype.UUID) (Location, error)
	GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error)
	GetIntegrationByID(ctx context.Context, id pgtype.UUID) (Integration, error)
	GetIntegrationByService(ctx context.Context, arg GetIntegrationByServiceParams) (Integration, error)
	GetLocationByID(ctx context.Context, id pgtype.UUID) (Location, error)
	GetLocationHistory(ctx context.Context, arg GetLocationHistoryParams) ([]Location, error)
	GetSessionByToken(ctx context.Context, tokenHash string) (Session, error)
	GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListEventsByTime(ctx context.Context, arg ListEventsByTimeParams) ([]Event, error)
	ListEventsByUserAndTime(ctx context.Context, arg ListEventsByUserAndTimeParams) ([]Event, error)
	ListIntegrations(ctx context.Context, userID pgtype.UUID) ([]Integration, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) error
	UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) error
	UpdateLastSync(ctx context.Context, id pgtype.UUID) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
